
stages:
  - build
  - test
  - sonar

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

sonar:
  stage: sonar
  script:
    - ./gradlew test sonar
  allow_failure: true
